---
- name: Manipulating Text files With Ansible
  hosts: all
  become: yes
  tasks:

  - name: Read from Database Report Sheet
    community.general.read_csv:
      path: database-report.csv
      key: HOSTNAME
      delimiter: ','
    register: machines
    delegate_to: localhost

  - ansible.builtin.debug:
      msg: "{{ item.value.HOSTNAME }}
            {{ item.value.IPRIV }}
            {{ item.value.IPUB }}
            {{ item.value.DATACENTER }}
            {{ item.value.OS }}"
    loop: "{{ machines.dict|dict2items }}"
    register: text

      
 